import type { WebContents } from 'electron';

/**
 * User-agent coherence.
 *
 * This was the top item in the security design's verification queue, and
 * measuring it found two real inconsistencies that made the privacy story
 * actively counterproductive:
 *
 *   1. **No client hints on the wire at all.** Aperture sent `User-Agent` and
 *      nothing else. Real Chrome sends `Sec-CH-UA`, `Sec-CH-UA-Mobile` and
 *      `Sec-CH-UA-Platform` on every single request. Claiming to be Chrome
 *      while sending zero client hints is a binary, trivially-checked anomaly
 *      — arguably a louder signal than a mismatched version, because there is
 *      no legitimate configuration that produces it.
 *
 *   2. **`navigator.userAgentData.brands` said "Chromium", never "Google
 *      Chrome".** So the UA string claimed Chrome while the JS API disagreed —
 *      the exact class of contradiction detectors look for, since they mostly
 *      do not measure values, they measure whether values agree.
 *
 * **The attempted fix did not work, and that changed the design.** CDP
 * `Emulation.setUserAgentOverride` takes a `userAgentMetadata` structure that
 * should drive both the headers and `navigator.userAgentData`. Electron accepts
 * it and reports success — and still sends no client hints. Confirmed by
 * control experiment: real Chromium sends all three to the same
 * `http://127.0.0.1` endpoint; Aperture sends none.
 *
 * Since the hints cannot be made to agree with a "Chrome" claim on this
 * platform, we stop making that claim. Aperture presents as **Chromium**,
 * which is what `navigator.userAgentData.brands` actually reports, so the
 * string and the API agree. The missing hints remain a tell — but one unusual
 * value beats a self-contradiction, because detectors mostly check agreement.
 *
 * What is never spoofed: the version. It comes from `process.versions.chrome`,
 * because the TLS ClientHello is generated by the real BoringSSL build and
 * cannot be faked from JavaScript. A version that disagrees with the engine is
 * contradicted below the JS layer entirely, which is the loudest tell there is.
 */

export interface UaProfile {
  userAgent: string;
  brands: { brand: string; version: string }[];
  fullVersionList: { brand: string; version: string }[];
  fullVersion: string;
  platform: string;
  platformVersion: string;
  architecture: string;
  bitness: string;
  model: string;
  mobile: boolean;
}

/** Windows 10/11 both report platformVersion >= 13 in Chrome's scheme. */
const WINDOWS_PLATFORM_VERSION = '15.0.0';

/**
 * Build a profile from the REAL Chromium version.
 *
 * The `Not;A=Brand` entry with its deliberately odd punctuation is part of
 * Chrome's GREASE scheme; omitting it is itself a fingerprint.
 */
export function buildUaProfile(chromeVersion: string): UaProfile {
  const major = chromeVersion.split('.')[0] ?? '150';

  // MEASURED, 2026-07-31: Electron accepts `Emulation.setUserAgentOverride`
  // with `userAgentMetadata` and reports success, but does NOT emit the
  // resulting `Sec-CH-UA` headers. Verified by control experiment — real
  // Chromium sends all three hints to the same http://127.0.0.1 endpoint;
  // Aperture sends none.
  //
  // So the client-hint half cannot be made to agree with the UA string on this
  // platform. Given that, claiming "Chrome" would be claiming something the
  // JS API contradicts (`brands` reports only Chromium) AND that the missing
  // headers contradict. Two contradictions are worse than one unusual value,
  // because detectors mostly check agreement rather than values.
  //
  // Therefore: present honestly as Chromium. The brands below are what
  // `navigator.userAgentData` actually reports, so the string and the API
  // agree. See docs/design/security.md for the full verification result.
  const brands = [
    { brand: 'Not;A=Brand', version: '8' },
    { brand: 'Chromium', version: major },
  ];

  const fullVersionList = [
    { brand: 'Not;A=Brand', version: '8.0.0.0' },
    { brand: 'Chromium', version: chromeVersion },
  ];

  return {
    // Chromium, not Chrome — and no "Electron/x.y.z", which the stock UA leaks.
    userAgent:
      `Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 ` +
      `(KHTML, like Gecko) Chromium/${chromeVersion} Safari/537.36`,
    brands,
    fullVersionList,
    fullVersion: chromeVersion,
    platform: 'Windows',
    platformVersion: WINDOWS_PLATFORM_VERSION,
    architecture: 'x86',
    bitness: '64',
    model: '',
    mobile: false,
  };
}

/**
 * Apply the profile to one tab, so the string, the headers and
 * `navigator.userAgentData` all come from the same source.
 *
 * Returns false if CDP is unavailable, in which case the caller should decide
 * whether an inconsistent UA is worse than no override at all. It is: an
 * inconsistent UA is a stronger signal than a truthful one.
 */
export async function applyUaProfile(
  wc: WebContents,
  p: UaProfile,
): Promise<boolean> {
  try {
    if (!wc.debugger.isAttached()) wc.debugger.attach('1.3');
    await wc.debugger.sendCommand('Emulation.setUserAgentOverride', {
      userAgent: p.userAgent,
      acceptLanguage: 'en-US,en;q=0.9',
      platform: 'Win32',
      userAgentMetadata: {
        brands: p.brands,
        fullVersionList: p.fullVersionList,
        fullVersion: p.fullVersion,
        platform: p.platform,
        platformVersion: p.platformVersion,
        architecture: p.architecture,
        model: p.model,
        mobile: p.mobile,
        bitness: p.bitness,
        wow64: false,
      },
    });
    return true;
  } catch {
    return false;
  }
}

/**
 * Is this profile self-consistent?
 *
 * Exported so it can be asserted in tests: the failure mode here is silent,
 * and a UA that contradicts its own client hints is worse than not spoofing.
 */
export function isCoherent(p: UaProfile): { ok: boolean; problems: string[] } {
  const problems: string[] = [];

  const uaVersion = /Chrom(?:e|ium)\/(\d+\.\d+\.\d+\.\d+)/.exec(p.userAgent)?.[1];
  if (!uaVersion) problems.push('UA string has no engine version');
  else if (uaVersion !== p.fullVersion) {
    // The loudest possible tell: TLS comes from the real BoringSSL build, so a
    // claimed version that disagrees with the engine is contradicted below the
    // JS layer entirely.
    problems.push(`UA version ${uaVersion} != fullVersion ${p.fullVersion}`);
  }

  const major = p.fullVersion.split('.')[0];
  for (const b of p.brands) {
    if (b.brand === 'Not;A=Brand') continue;
    if (b.version !== major) {
      problems.push(`brand ${b.brand} version ${b.version} != major ${major}`);
    }
  }

  // The UA must not claim a brand the client hints fail to corroborate.
  // Claiming Chrome while `navigator.userAgentData.brands` lists only Chromium
  // is the exact contradiction detectors look for.
  const claimsChrome = p.userAgent.includes('Chrome/');
  if (claimsChrome && !p.brands.some((b) => b.brand === 'Google Chrome')) {
    problems.push('UA claims Chrome but brands do not list "Google Chrome"');
  }

  const brandNames = new Set(p.brands.map((b) => b.brand));
  for (const b of p.fullVersionList) {
    if (!brandNames.has(b.brand)) {
      problems.push(`fullVersionList has ${b.brand}, brands does not`);
    }
  }

  if (p.userAgent.includes('Windows') && p.platform !== 'Windows') {
    problems.push('UA claims Windows, platform does not');
  }

  if (p.userAgent.includes('Electron')) {
    problems.push('UA leaks Electron');
  }

  return { ok: problems.length === 0, problems };
}
